# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='whlianjiachengjiao',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='详情Url')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('houseArea', models.CharField(max_length=32, verbose_name='房屋区域')),
                ('communityName', models.CharField(max_length=512, verbose_name='社区名称')),
                ('houseType', models.CharField(max_length=32, verbose_name='房屋类型')),
                ('houseSize', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='房屋面积')),
                ('dealPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='交易价格')),
                ('unitPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='单价')),
                ('dealDate', models.DateField(verbose_name='交易日期')),
                ('onPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='挂牌价格')),
                ('dealCycleDay', models.IntegerField(verbose_name='交易周期')),
                ('houseDirection', models.CharField(max_length=32, verbose_name='朝向')),
                ('houseDecoration', models.CharField(max_length=32, verbose_name='装修情况')),
                ('houseFlood', models.CharField(max_length=64, verbose_name='楼层和年代')),
            ],
            options={
                'verbose_name': '武汉链家成交数据',
                'verbose_name_plural': '武汉链家成交数据',
            },
        ),
        migrations.CreateModel(
            name='whlianjiaershoufang',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='详情Url')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('onPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='挂牌价格')),
                ('unitPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='单价')),
                ('houseArea', models.CharField(max_length=32, verbose_name='房屋区域')),
                ('communityName', models.CharField(max_length=512, verbose_name='社区名称')),
                ('houseType', models.CharField(max_length=32, verbose_name='房屋类型')),
                ('houseSize', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='房屋面积')),
                ('houseDirection', models.CharField(max_length=32, verbose_name='朝向')),
                ('houseDecoration', models.CharField(max_length=32, verbose_name='装修情况')),
                ('houseFlood', models.CharField(max_length=64, verbose_name='楼层和年代')),
                ('housePosition', models.CharField(max_length=64, verbose_name='位置')),
                ('visit', models.IntegerField(verbose_name='交易周期')),
                ('onDate', models.DateField(verbose_name='交易日期')),
            ],
            options={
                'verbose_name': '武汉链家二手房数据',
                'verbose_name_plural': '武汉链家二手房数据',
            },
        ),
    ]
