# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ['-create_date'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
