# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190626_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SClass',
            fields=[
                ('class_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='班级ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('grade', models.IntegerField(verbose_name='年级')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
                'ordering': ['class_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='学生ID')),
                ('s_name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('s_age', models.IntegerField(verbose_name='学生年龄')),
                ('s_sex', models.IntegerField(default=0, verbose_name='性别 0 男  1 女')),
                ('s_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, to='user.SClass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
